/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yagi2' at '16/12/10 18:45' with Gradle 2.14.1
 *
 * @author yagi2, @date 16/12/10 18:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
